### ISSUE TITLE
FIx settings resetting after reload

### ISSUE THREAD

**Issue by jaksia** [Stanko2/arnold#36]

**Comment by Stanko2** [comment]
Can't reproduce, probably broken because of older incompatible preferences save

**Comment by jaksia** [comment]
Successfully reproduced. Only some settings are affected, specifically all tool settings apart from scoring.

Tested on latest `dev`, using Chrome (v105.0.5195.127), with all previously stored data cleared.

**Comment by jaksia** [comment]
@Stanko2 please look into this, it's quite important and solution evaulation starts this week

**Comment by jaksia** [comment]
Probably related to https://p-mat.slack.com/archives/C045J6J13AS/p1667332151438389
![image](https://user-images.githubusercontent.com/35041897/199437212-38a13531-0bc4-401d-903f-f94b5efd4031.png)

**Comment by jaksia** [comment]
@Stanko2 please look into this. I would try to fix it but I'm not as experienced in Vue as you are and I'm not sure how some things work.
